- CHANGELOG.md
- package.json
If applied correctly the PR will:
> Prepare for 0.2.0 release

- .husky/commit-msg
- .husky/pre-commit
- .prettierignore
- commitlint.config.js
- package.json
> Configure husky to do pre commit format + linting checks

- CONTRIBUTING.md
> Test release creation

- packages/core/lib/analysis/static/TargetPool.ts
- packages/core/lib/event/ListenerInterface.ts
- packages/core/lib/event/ProgramState.ts
- packages/core/lib/plugin/SearchAlgorithmPlugin.ts
- packages/core/lib/search/metaheuristics/RandomSearch.ts
- packages/core/lib/search/metaheuristics/SearchAlgorithm.ts
- packages/core/lib/search/metaheuristics/evolutionary/EvolutionaryAlgorithm.ts
- packages/core/lib/search/metaheuristics/evolutionary/MOSAFamily.ts
- packages/core/lib/search/metaheuristics/evolutionary/NSGAII.ts
- packages/core/test/search/metaheuristics/MOSA.test.ts
- plugins/plugin-core-sfuzz/lib/Sfuzz.ts
- plugins/plugin-core-sfuzz/lib/SfuzzPlugin.ts
> Add event emissions in search algorithm and targetpool

- packages/core/lib/analysis/static/ActionDescription.ts
- packages/core/lib/analysis/static/TargetPool.ts
- packages/core/lib/analysis/static/targetUtil.ts
> Refactor get function map

- packages/core/lib/Configuration.ts
- packages/core/lib/util/fileSystem.ts
> Add global output directory and rename test output directory

- libraries/README.md
- libraries/base-testing-tool/package.json
- libraries/cfg-core/package.json
- libraries/cli-graphics/package.json
- libraries/cli/package.json
- libraries/core/package.json
- libraries/logging/package.json
- libraries/module/package.json
- plugins/plugin-core-graphing/package.json
- plugins/plugin-core-sfuzz/package.json
- tools/init/README.md
- tools/init/package.json
> Make sure that the README.md file is always added to the package

- libraries/core/lib/search/metaheuristics/evolutionary/NSGAII.ts
NSGAII had some major bugs that this PR fixes.
> Repair NSGAII

- libraries/base-testing-tool/lib/Configuration.ts
- tools/init/lib/commands/config.ts
These changes are required to allow:
- the init tool to actually gather all options from all tools/plugins/commands etc.
- the javascript tool to add the configurations options properly such that they are visible to the plugins/other modules
> Make sure that the configuration object is usable by the tool implementation

- plugins/plugin-core-metric-middleware-file-writer/lib/middleware/FileWriterMetricMiddleware.ts
- plugins/plugin-core-metric-middleware-file-writer/lib/plugins/FileWriterMetricMiddlewarePlugin.ts
- plugins/plugin-core-metric-middleware-file-writer/test/example.test.ts
- tools/base-language/lib/Launcher.ts
- tools/base-language/lib/Metrics.ts
Also prepends the fid to each line and file in the metrics output
> Add more metrics to the output

- libraries/search/index.ts
- tools/base-language/lib/TestingToolModule.ts
- tools/base-language/lib/plugins/objective-managers/TrackingObjectiveManagerPlugin.ts
- tools/base-language/lib/presets/RandomSearchPreset.ts
Add a preset to make use of the random search algorithm.
> Implement random search preset

- libraries/search/lib/objective/BranchObjectiveFunction.ts
- libraries/search/lib/objective/heuristics/ApproachLevel.ts
The statement count was not working and was actually making the results worse.
This PR fixes the statement count.
> Patch statement count distance

- libraries/module/index.ts
- libraries/module/lib/ModuleManager.ts
- libraries/module/lib/util/extractArgumentValues.ts
- package-lock.json
- package.json
- tools/cli/bin.ts
- tools/init/lib/commands/config.ts
Saves the configuration settings to .syntest.json file in the fid folder.
Closes #317
> Save configuration settings to output folder

- libraries/search/lib/operators/procreation/DefaultProcreation.ts
Adds up to 20% freshly sampled individuals during the offspring creation phase.
> Add more random individuals during search

- tools/base-language/lib/Configuration.ts
- tools/base-language/lib/Launcher.ts
Removes some old unused configuration options
> Remove unused options

- libraries/search/lib/objective/BranchObjectiveFunction.ts
This PR will make it such that the distance to an objective is structured as followed:
XX.YYZZZZ
Where:
- XX is the approach level
- YY is the fraction of uncovered statements within a block
- ZZZZ is the branch distance
Originally the distance was structured without the YY part (XX.ZZZZ)
> Modify statements fraction

- tools/base-language/index.ts
- tools/base-language/lib/Configuration.ts
- tools/base-language/lib/FileSelector.ts
- tools/base-language/lib/Launcher.ts
Changes the include parameter to target-include
Changes the exclude parameter to target-exclude
Adds the analysis-include parameter
Adds the analysis-exclude parameter
Adds a file selector class
> Feat analysis include exclude config parameter

- libraries/search/lib/EncodingRunner.ts
- libraries/search/lib/objective/managers/ObjectiveManager.ts
- tools/base-language/lib/plugins/event-listeners/SearchPerformanceListener.ts
Removes the unnecessary subject argument from runner.
> Feat remove subject from runner

- .eslintignore
- CITATION.cff
The citation file shows a button for how to cite the work on GitHub.
> Add citation config

- libraries/module/lib/extension/Preset.ts
- plugins/plugin-search-algorithm-experimental/lib/sfuzz/SFuzzPreset.ts
- plugins/plugin-search-algorithm-experimental/lib/speaii/presets/DynaMOSASPEAIIPreset.ts
- plugins/plugin-search-algorithm-experimental/lib/speaii/presets/MOSASPEAIIPreset.ts
- plugins/plugin-search-algorithm-experimental/lib/speaii/presets/SPEAIIPreset.ts
- tools/base-language/lib/presets/DynaMOSAPreset.ts
- tools/base-language/lib/presets/MOSAPreset.ts
- tools/base-language/lib/presets/NSGAIIPreset.ts
- tools/base-language/lib/presets/RandomSearchPreset.ts
Modifies the preset logic to give warnings when options are overridden.
> Refactor preset logic

- libraries/cli-graphics/lib/UserInterface.ts
- tools/base-language/lib/plugins/event-listeners/SearchProgressBarListener.ts
The spacing was wrong in the loading bar.
I also added an indicator for the budget.
> Improve UI loading bar

- libraries/search/lib/algorithms/evolutionary/MOSAFamily.ts
- tools/base-language/lib/Launcher.ts
Added context to one of the thrown errors.
Made sure that error context is also logged/printed when present.
> Improve error handling

- libraries/search/lib/objective/branch/branchObjectiveExtraction.ts
- libraries/search/lib/objective/path/pathObjectiveExtraction.ts
Made sure that it is possible to add function objectives as parents of path/branch objectives.
> Use correct hierarchy for objectives

- plugins/plugin-event-listener-state-storage/lib/StateStorage.ts
The sortation function did not split on the right characters.
> Repair sortation function

- tools/base-language/lib/plugins/event-listeners/SearchMetricListener.ts
The newly added path coverage was not being recorded.
This PR fixes that.
> Record path coverage

- .github/workflows/pr-test.yml
We are reaching API rate limits.
> Remove test reporter
