- package.json
The github build (and my local build as well) was failing because
```
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
```
Upgrading the `ts-node` and `@types/nodes` dependencies fixes this. See [stackoverflow](https://stackoverflow.com/questions/72488958/false-expression-non-string-value-passed-to-ts-resolvetypereferencedirective)
Also updated `mocha` to get rid of an audit warning.
> Update dependencies to fix github build

- package.json
- src/util/logger.ts
Extension of #99 which helps to get rid of the warning raised during tests:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```
The simple change is in commit 87b0bf9f8b539db626076202c36935e37366255c
> Close existing logger before creating new one.

- .github/workflows/build.yml
- .github/workflows/publish.yml
The list of LTS node versions in the build workflow was outdated. The new list matches the current supported LTS versions found here: https://nodejs.org/en/about/releases/
> Update node versions in build workflow

- src/ui/UserInterface.ts
- test/search/metaheuristics/MOSA.test.ts
- test/search/operators/CrowdingDistance.test.ts
- test/search/operators/DominanceComparator.test.ts
- test/search/operators/FasNonDomSorting.test.ts
- test/search/operators/TournamentSelection.test.ts
The UI is used as a logging API and used in many classes. But its setup requires a tricky series of calls setting global variables.
Replace this setup by a simple (Sinon) mock of the UI. Due to a limitation in Sinon, this meant that the protected `silent`/`verbose` field of the `UserInterface` class had to be public, but that seems worth the simplicity in return. Also, these properties don't seem to be _used_ anywhere, so maybe they can be removed?
Using a mock also makes it mandatory to explicitly set properties that steer the algorithms, making the tests self documenting and less fragile. Setting such a property was only needed for one test case: Testing preference sorting in MOSA.
> Simplify test setup by mocking the user interface

- .github/workflows/build.yml
- The CI was only running on the main, but we now added a develop branch
- The CI was not using the latest Node.JS version
> infra: update CI infrastructure settings

- tsconfig.json
This file is not necessary anymore since all packages have been moved to the monorepo structure.
> build: remove unused TS config file

- .github/workflows/publish-prerelease.yml
- .github/workflows/version-release.yml
- lerna.json
This PR will make sure that the beta releases do not create tags and do not end up in the changelogs.
This is the only way to have auto generated changelogs for now.
More info on the changelog bug:
https://github.com/lerna/lerna/issues/2248
> Fix versioning workflow

- .github/workflows/main-build.yml
- .github/workflows/main-quality.yml
- .github/workflows/main-test.yml
- .github/workflows/pr-build.yml
- .github/workflows/pr-test.yml
- .github/workflows/publish-prerelease.yml
- .github/workflows/publish-release.yml
- .github/workflows/version-release.yml
Previously, we only had build and quality workflows for PRs. To allow us to show build and quality status badges on the README, we need to also run these workflows on the main branch.
Closes #246 
Closes #243
> Add main branch workflows

- .github/workflows/main-test.yml
- .github/workflows/pr-test.yml
Coveralls is having trouble parsing the LCOV files generated during the test and coverage scripts. According to this [issue](https://github.com/lemurheavy/coveralls-public/issues/1593#issuecomment-1042117714), the base-path is necessary next to the path to LCOV to make sense of the data in the LCOV file. This was unclear from the documentation
> Add base-path parameter to Coveralls

- libraries/cfg-core/lib/ControlFlowGraphFactory.ts
The generic variable S was misplaced on the function instead of the class; this makes it hard to change what S exactly is.
The function also requires a filePath since the CFG factory will make use of the babel visitor in the javascript implementation which also requires a filePath to be specified.
> Patch cfg factory

- .github/workflows/main-build.yml
- .github/workflows/main-quality.yml
- .github/workflows/main-test.yml
By canceling concurrent builds for the main branch, the status badges and the coverage statistics will show a failed build. This was done initially for the PR builds as there, it would not make sense to build commits rapidly done after each other since this is the development stage.
> Remove concurrent build canceling for main branch

- tools/base-language/lib/Configuration.ts
Search algorithms were crashing if no secondary objective was defined. This happened by a name mismatch in the Yargs configuration
> Secondary objectives arg was not matching

- libraries/search/lib/Encoding.ts
- libraries/search/lib/objective/BranchObjectiveFunction.ts
- libraries/search/lib/objective/managers/ObjectiveManager.ts
The branch distance became NaN because the branch distance calculation contains a bug currently.
This PR adds several guards to check for this behavior and implements a temporary "hack" as a workaround to the problem.
This "hack" will be removed at a later point in time.
> Fix branch distance NaN bug

- libraries/search/lib/objective/managers/StructuralUncoveredObjectiveManager.ts
- tools/base-language/lib/TestingToolModule.ts
- tools/base-language/lib/plugins/objective-managers/StructuralUncoveredObjectiveManagerPlugin.ts
The new structural uncovered objective manager was not registered correctly making it impossible to use.
> Fix new objective manager plugin

- libraries/search/lib/objective/BranchObjectiveFunction.ts
- libraries/search/lib/objective/managers/ArchiveBasedObjectiveManager.ts
- libraries/search/lib/objective/managers/ObjectiveManager.ts
- libraries/search/lib/objective/managers/PopulationBasedObjectiveManager.ts
- libraries/search/lib/objective/managers/SimpleObjectiveManager.ts
- libraries/search/lib/objective/managers/StructuralObjectiveManager.ts
- libraries/search/lib/objective/managers/StructuralUncoveredObjectiveManager.ts
- libraries/search/lib/objective/managers/TrackingObjectiveManager.ts
- libraries/search/lib/objective/managers/UncoveredObjectiveManager.ts
Currently, when a new objective is covered that adds additional objectives (through the structural objective manager) these objectives are not evaluated until the next encoding.
This PR recursively evaluates these newly added objectives.
> Structural manager optimalization

- libraries/search/lib/objective/heuristics/ApproachLevel.ts
The approach level was now considering every trace whether it was covered or not. 
Impact: this caused the approach level to always be zero.
We now filter out the traces that don't have any hits.
> Patch approach level calculation

- libraries/logging/lib/logger.ts
The word `singleton` was misspelled
> Fix variable naming in logger

- tools/base-language/lib/TestingToolModule.ts
- tools/base-language/lib/plugins/event-listeners/SearchProgressBarListener.ts
The search progress bar event listener was located in the SynTest JavaScript repo. However, nothing in the file was particular to JavaScript. Therefore, I have moved it to the Core
> Move search progress bar to the core

- tools/base-language/lib/Configuration.ts
- tools/base-language/lib/Launcher.ts
Since the constant pool is specific to the different languages. We have moved this configuration over to those packages.
> Remove constant pool configuration from core

- tools/base-language/lib/Launcher.ts
Currently, when an error has been thrown the exit function of the launcher is not called.
To ensure everything is properly cleaned up it is important that the exit function is actually called when an error is thrown.
> Enforce gracefull exit

- tools/base-language/lib/plugins/event-listeners/SearchMetricListener.ts
Currently, the namespaces are set to the subject name (i.e., name of the file), however, when two files have the same name, this means these files are put together when processing the files.
> Duplicate search namespaces

- libraries/search/lib/objective/BranchObjectiveFunction.ts
Currently, when there are no execution traces the objective functions make various calculations that are not necessary as these will never be needed. This PR makes is so that the whole calculation is short-circuited when there are no traces.
> Do not calculate approach level when there are no traces

- libraries/metric/lib/Metric.ts
- libraries/metric/lib/MetricManager.ts
- libraries/metric/lib/PropertyTypes.ts
- libraries/metric/lib/util/diagnostics.ts
- libraries/search/lib/objective/ObjectiveFunction.ts
- libraries/search/lib/objective/managers/ObjectiveManager.ts
- plugins/plugin-core-event-listener-state-storage/lib/StateStorage.ts
- plugins/plugin-core-event-listener-state-storage/lib/StateStorageEventListenerPlugin.ts
- plugins/plugin-core-metric-middleware-file-writer/lib/middleware/FileWriterMetricMiddleware.ts
- plugins/plugin-core-metric-middleware-statistics/lib/Metrics.ts
- plugins/plugin-core-metric-middleware-statistics/lib/middleware/StatisticsMetricMiddleware.ts
- plugins/plugin-core-metric-middleware-statistics/lib/plugins/StatisticsMetricMiddlewarePlugin.ts
- plugins/plugin-core-metric-middleware-statistics/lib/statistics/AUC.ts
- plugins/plugin-core-metric-middleware-statistics/lib/statistics/Statistic.ts
- tools/base-language/lib/Metrics.ts
- tools/base-language/lib/plugins/event-listeners/SearchMetricListener.ts
Implements a way to:
- store the final covered and uncovered objectives to file.
- store the distance to each objective per timestep to the metric manager.
Renamed:
- seriesName -> name
- seriesType -> seriesUnit
- distributionName -> name
- property -> name
Added metric type: "series measurement"
> Store covered data at end of search

- libraries/prng/lib/prng.ts
Currently, the seeded PRNG is only used internally by us. However, the library we use for this has an option to overwrite Math.random(). This would allow us to catch any random call that we might have missed in our code but also calls to Math.random() in our dependencies.
We need to be careful though that this does not have unwanted side affects on our dependencies, but this should not be the case.
> Make seeded prng global

- libraries/search/lib/budget/BudgetListener.ts
- libraries/search/lib/budget/BudgetManager.ts
- libraries/search/lib/objective/managers/ObjectiveManager.ts
The evaluation argument is never used in the budgets and therefore can be removed. This allows us to clean up the objective manager a bit.
Originally, we wanted to remove all arguments to the budgets. However, as it turns out the stagnation budget requires the search algorithm to determine if any progress was made
> Remove evaluation argument from budgets

- libraries/search/index.ts
- libraries/search/lib/ExecutionResult.ts
- libraries/search/lib/Trace.ts
- libraries/search/lib/objective/BranchObjectiveFunction.ts
- libraries/search/lib/objective/ExceptionObjectiveFunction.ts
- libraries/search/lib/objective/heuristics/ApproachLevel.ts
- libraries/search/lib/objective/heuristics/BranchDistance.ts
- libraries/search/lib/objective/managers/ArchiveBasedObjectiveManager.ts
- libraries/search/lib/objective/managers/ObjectiveManager.ts
- libraries/search/lib/objective/managers/PopulationBasedObjectiveManager.ts
* Rename Datapoint -> Trace
* In ExecutionResult: getException -> getError (actually returns an error object instead of string)
* In ExecutionResult: hasException -> hasException
* Removes condition_ast from traces
* Uses the stacktrace to generate exception hashes
> Refactor execution results

- libraries/search/lib/Encoding.ts
Assertions are specific to testing and thus do not belong in the core search library.
> Remove assertions from core

- .zenodo.json
The Zenodo configuration file automatically configures the Zenodo metadata for the software entity publication.
> Add zenodo config

- tools/base-language/lib/Configuration.ts
- tools/base-language/lib/presets/RandomSearchPreset.ts
The random preset used the wrong default value for the type inference mode.
I added a flag for the de-duplication step.
> Add config parameter and fix random search preset
